version: '3.7'
services:

  cloud-game:
    build: .
    image: cloud-game-local
    container_name: cloud-game-local
    environment:
      - DISPLAY=:99
      - MESA_GL_VERSION_OVERRIDE=3.3
      - CLOUD_GAME_WEBRTC_ICEPORTS_MIN=20900
      - CLOUD_GAME_WEBRTC_ICEPORTS_MAX=21000
      - CLOUD_GAME_WEBRTC_ICEIPMAP=54.161.241.182
      # - PION_LOG_TRACE=all
    ports:
      - 8000:8000
      - 9000:9000
      - 20900-21000:20900-21000/udp
    command: >
      bash -c "Xvfb :99 & coordinator --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5"
    volumes:
      # keep cores persistent in the cloud-game_cores volume
      - cores:/usr/local/share/cloud-game/assets/cores
      - ${CLOUD_GAME_GAMES_PATH:-./assets/games}:/usr/local/share/cloud-game/assets/games
      - type: bind
        source: upgames-19cbf-firebase-adminsdk-q10xz-e057e4543a.json
        target: /opt/upgames-19cbf-firebase-adminsdk-q10xz-e057e4543a.json

volumes:
  cores:
