version: '3.7'
services:

  cloud-game:
    build: .
    image: cloud-game-local
    container_name: cloud-game-local
    environment:
      - DISPLAY=:99
      - MESA_GL_VERSION_OVERRIDE=4.5
      - CLOUD_GAME_WEBRTC_ICEPORTS_MIN=20900
      - CLOUD_GAME_WEBRTC_ICEPORTS_MAX=21000
      - CLOUD_GAME_WEBRTC_ICEIPMAP=54.161.241.182
      - CLOUD_GAME_COORDINATOR_DEBUG=true
      - CLOUD_GAME_WORKER_DEBUG=true
      # - PION_LOG_TRACE=all
    ports:
      - "8000:8000"
      - "9000:9000"
      - "20900-21000:20900-21000/udp"
    command: >
      bash -c "Xvfb :99 & coordinator --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5 & worker --v=5"
    volumes:
      - ./assets/cores:/usr/local/share/cloud-game/assets/cores
      - ./assets/games:/usr/local/share/cloud-game/assets/games
      - x11:/tmp/.X11-unix
      - type: bind
        source: upgames-19cbf-firebase-adminsdk-q10xz-e057e4543a.json
        target: /opt/upgames-19cbf-firebase-adminsdk-q10xz-e057e4543a.json

  xvfb:
    image: kcollins/xvfb:latest
    volumes:
      - x11:/tmp/.X11-unix
    command: [ ":99", "-screen", "0", "320x240x16" ]

  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: yester
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "psql", "-U", "postgres", "-l" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  x11:
